### ISSUE TITLE
How can i find already built version?

### ISSUE THREAD

**Issue by Numenorean** [mrts/burp-suite-http-proxy-history-viewer#9] opened 2021-07-27 09:45 UTC

**Comment by mrts** [comment] 2021-07-27 15:19
There is no official release yet, the app is unfortunately unfinished.

Let's see, maybe someone will pick it up one day, the codebase is small and easy to work with and there are just a couple of small changes required to make it work.

**Comment by mrts** [comment] 2021-07-27 15:20
Closing as duplicate of #8.

**Closed as completed by mrts** 2021-07-27 15:20 UTC
